In [1]:
import torch
import torch.nn as nn

class MyClass(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.weight = nn.Parameter(torch.tril(torch.randn(5,5)))
        self.mask = torch.tril(torch.ones_like(self.weight))

    def forward(self, x):
        out = (self.weight * self.mask).matmul(x)
        return out

In [22]:
data = torch.randn(5,4)
model = MyClass()
model.weight * model.mask

tensor([[ 0.0167,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 1.7769,  0.3381,  0.0000,  0.0000,  0.0000],
        [-1.8882, -0.2545, -0.7118,  0.0000,  0.0000],
        [ 0.6531, -0.6797, -0.5592,  0.1356,  0.0000],
        [ 1.0836,  1.5714, -0.7795,  0.4477, -0.3124]], grad_fn=<MulBackward0>)

In [3]:
out = model(data)
out.sum().backward()

optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
loss = torch.norm(out)

In [4]:
for epoch in range(5):
    #for images, _ in train_loader: 
          
        out = model(data)
        loss = torch.norm(out)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

In [18]:
weight = nn.Linear(5,3, bias=False)
mask = torch.tril(torch.ones_like(weight.weight))
z = torch.randn(20,5)
weight.weight

Parameter containing:
tensor([[ 0.3472,  0.0371, -0.1788,  0.2298, -0.2936],
        [ 0.1103, -0.3629, -0.4212,  0.0350,  0.1594],
        [ 0.4251, -0.3227,  0.1771, -0.2735,  0.2842]], requires_grad=True)

In [21]:
out1 = torch.matmul(z, (mask * weight.weight).T)
out3 = torch.mm(z, (mask * weight.weight).T)
out2 = weight(z)

In [7]:
model.weight.grad

tensor([[-0.0387,  0.0000,  0.0000,  0.0000,  0.0000],
        [-0.0697, -0.0681,  0.0000,  0.0000,  0.0000],
        [-0.0095,  0.1820, -0.3771,  0.0000,  0.0000],
        [-0.0250,  0.1712,  0.1880, -0.8890,  0.0000],
        [-0.3240,  0.5508,  1.0027, -2.6819, -0.5179]])

In [57]:
y = torch.tensor([[1.,2.],[3.,4.]], requires_grad=True)

In [58]:
x = torch.tensor([[1.,0.],[0.,1.]])

In [59]:
z = x*y

In [60]:
z = torch.tensordot(x,y)

In [61]:
z.backward()


In [62]:
x.grad

In [63]:
y.grad

tensor([[1., 0.],
        [0., 1.]])

In [36]:
z = torch.randn(10, 5)
U1 = torch.randn(5)
U2 = torch.randn(5)
U3 = torch.randn(5)

In [39]:
U1.unsqueeze(2)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [37]:
x1 = U1 * z
x2 = U2 * z
x3 = U3 * z

In [41]:
x_outer1 = torch.einsum('bi,bj->bij',(x1, x2))

In [44]:
x_12 = torch.sum(x_outer1, 1)

In [45]:
x_outer2 = torch.einsum('bi,bj->bij',(x_12, x3))

In [46]:
x_123 = x_123 = torch.sum(x_outer2, 1)

In [47]:
x_12+0.00001

tensor([[ 6.1251e-01,  1.3459e+00,  3.9160e-02, -5.1343e-01,  2.4346e-01],
        [ 3.9045e+00,  1.9004e+00,  5.7950e-02, -4.4516e-01, -4.6823e-02],
        [-2.7351e-01,  3.7252e-01, -3.1767e-02,  2.3435e-01, -3.1863e-01],
        [-1.0343e+00,  1.2859e+00,  1.1450e-01, -3.0797e-01, -2.3078e-01],
        [-3.5838e-01,  4.4000e+00,  2.4451e-01,  2.4578e+00, -1.1770e+00],
        [-1.6321e-02, -8.4877e-03, -2.1962e-04,  1.3010e-02, -4.9489e-03],
        [ 1.0477e+00, -5.7436e-01, -9.8630e-03,  7.6239e-01, -3.1557e-01],
        [-3.7253e-01, -2.1129e-01, -6.0105e-02, -2.5007e-01, -1.0371e+00],
        [-4.9378e-01,  7.0809e-01,  2.1721e-02,  8.0919e-01, -6.6469e-02],
        [-3.1889e+00,  3.6697e+00, -1.5246e-02,  7.5196e-01, -1.6227e+00]])

In [33]:
x_outer1 = torch.outer(x1, x2)

In [34]:
x_12 = torch.sum(x_outer1, 1)

In [35]:
x_outer2 = torch.outer(x3, x_12)
x_123 = torch.sum(x_outer2, 1)